#+TITLE: FAU Forge: 0install feeds

* Introduction
  [[http://0install.net/][Zero Install]] is a distributed software distribution system that can
  be used to securely distribute packages, whether in binary form or
  source, to be compiled on the target machine.

  We have chosen to use this mechanism to distribute the building
  blocks of the software forge, to provide a uniform installation
  mechanism regardless of the underlying platform.

* Available feeds
** Git
   The Git feed wraps around the system packaging (git on RPM-based systems, git-core on Debian-based ones).
   It has not been published yet.

* TBA
** self-compiled
   These will contain packages that are compiled on the target machines. For
   the default deployment platform (Ubuntu 10.04 LTS) we will also provide
   pre-built packages
*** Apache
*** Mailman
    Depends on Postfix and Python
*** MediaWiki
    Depends on Apache and PostgreSQL
*** PostgreSQL
** Wrappers
   These feeds will just contain wrappers around the respective system
   packages
*** Python
*** Postfix

* Publishing
** Location
   All feeds will be published to
   http://faui2o1a.informatik.uni-erlangen.de/interfaces/2010/NAME

   where the feed name is substituted for NAME.

   Use =make publish= to publish the feeds to the server. You'd need to provide
   your SSH key to [[mailto:michel.salim@informatik.uni-erlangen.de][Michel]] or [[mailto:carsten.kolassa@informatik.uni-erlangen.de][Carsten]] for this to succeed.
